### ISSUE TITLE
error

### ISSUE THREAD

**Issue by intellinux** [IRIS-Team/IRIS#7]
root@ubuntu:/usr/share/IRIS# python3 -m iris
Traceback (most recent call last):
  File "/usr/lib/python3.8/runpy.py", line 185, in _run_module_as_main
    mod_name, mod_spec, code = _get_module_details(mod_name, _Error)
  File "/usr/lib/python3.8/runpy.py", line 144, in _get_module_details
    return _get_module_details(pkg_main_name, error)
  File "/usr/lib/python3.8/runpy.py", line 111, in _get_module_details
    __import__(pkg_name)
  File "/usr/share/IRIS/iris/__init__.py", line 1, in <module>
    from iris.app import Application
  File "/usr/share/IRIS/iris/app/__init__.py", line 1, in <module>
    from .application import Application
  File "/usr/share/IRIS/iris/app/application.py", line 9, in <module>
    from iris.module import Module, ModuleWrapper
  File "/usr/share/IRIS/iris/module/__init__.py", line 2, in <module>
    from .wrapper import ModuleWrapper
  File "/usr/share/IRIS/iris/module/wrapper.py", line 7, in <module>
    class ModuleWrapper:
  File "/usr/share/IRIS/iris/module/wrapper.py", line 52, in ModuleWrapper
    def execute_method_parameters(self) -> dict[str: type]:
TypeError: 'type' object is not subscriptable

**Comment by rpie** [comment]
this is currently a error with python 3.8 try running with python 3.9 `python3.9 -m iris` 
Please tell me if this fixes the issue :)

- HellSec

**Comment by rpie** [comment]
Fixed this issue, was the location of "home" in linux kernels.
